[tool.poetry]
name = "spectra6-backend"
version = "0.1.0"
description = "Backend for Spectra, an advanced AI assistant."
authors = ["Vesryin <vesryin@gmail.com>"]
packages = [{include = "app", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
responder = "^2.0.7"
typesystem = "==0.2.5"
psycopg2-binary = "^2.9.0"
pgvector = "^0.2.0"
sentence-transformers = "^2.2.0"
uvicorn = "<0.13.3"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
pytest-mock = "^3.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
